language: php
php:
#  - 5.2
  - 5.3
  - 5.4

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script: sh travis/prepare.sh

script: sh travis/run-test.sh

notifications:
  email:
    - reeze.xia@gmail.com
